---
- name: Add New Logic Monitor Collectors
  remote_user: mklserveradmin
  become: yes
  become_method: sudo
  tasks:
# Add new collectors into the /etc/snmp/snmpd.conf file
  ansible.builtin.blockinfile:
    path: /etc/snmp/snmpd.conf
    backup: yes 
    block:  
      rocommunity M@rk3lc0rp-RO 10.65.135.184
      rocommunity M@rk3lc0rp-RO 10.65.135.40
    insertafter:  
# configuration will add multiple rich rule to Firewalld
- name: Rich Rules
  ansible.posix.firewalld:
    rich_rule: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
  - 'rule family=ipv4 source address=10.65.135.184 port port=161 protocal=upd accept'
  - 'rule family=ipv4 source address=10.65.135.40 port port=161 protocal=upd accept'
# This will Reload the firewalld service after modifications have been made
- name: Always Reload firewalld #ansible.builtin.service can also be used
  ansbile.builtin.systemd_service:
    name: firewalld
    state: reloaded 
